name: M3U Otomatik Guncelleme

on:
  workflow_dispatch: # Manuel başlatmak için
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik kontrol eder

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Repoya yazma izni verir

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: pip install requests

      - name: M3U Dosyasını İndir
        run: python download_m3u.py

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tv.m3u
          # Eğer dosya değişmişse commit at ve pushla
          if git diff --cached --quiet; then
            echo "Herhangi bir değişiklik yok, işlem atlanıyor."
          else
            git commit -m "Otomatik Güncelleme: tv.m3u yenilendi"
            git push
          fi
